// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKZqEHcXpa8vS5sd2d3HocxKwXZqCvijY',
    appId: '1:189636867451:web:8eb6b7b5db45c88a6879de',
    messagingSenderId: '189636867451',
    projectId: 'nomad-tiktok-hary',
    authDomain: 'nomad-tiktok-hary.firebaseapp.com',
    storageBucket: 'nomad-tiktok-hary.appspot.com',
    measurementId: 'G-G7D0G6WLX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKFa2xyLxcxnPcM5K9Vr_Kq9t981HM32U',
    appId: '1:189636867451:android:cd8ae6e8ab9326846879de',
    messagingSenderId: '189636867451',
    projectId: 'nomad-tiktok-hary',
    storageBucket: 'nomad-tiktok-hary.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI207sQmB74BG-yM7P1qpUOaMgtGFSNRY',
    appId: '1:189636867451:ios:10ecf748a41594bf6879de',
    messagingSenderId: '189636867451',
    projectId: 'nomad-tiktok-hary',
    storageBucket: 'nomad-tiktok-hary.appspot.com',
    iosBundleId: 'com.tiktokharu.harutik',
  );

}